mysite/common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

app_name = "common"

urlpatterns = [
    path(
        "login/",
        auth_views.LoginView.as_view(template_name="common/login.html"),
        name="login",
    ),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
]

mysite/config/urls.py
from django.contrib import admin
from django.urls import path, include
from news import views as views_news

urlpatterns = [
    path("", views_news.index),
    path("admin/", admin.site.urls),
    path("common/", include("common.urls")),
    path("news/", include("news.urls")),
]

mysite/news/urls.py
from django.urls import path
from . import views

app_name = "news"

urlpatterns = [
    path("", views.index, name="index"),
    path("search/", views.news_search, name="news_search"),
]

mysite/news/models.py
from django.db import models

# Create your models here.

mysite/common/views.py
from django.shortcuts import render

# Create your views here.

mysite/news/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required


@login_required(login_url="common:login")
def index(request):
    """
    뉴스 검색 화면으로 리다이렉트한다.
    """
    return redirect("news:news_search")


@login_required(login_url="common:login")
def news_search(request):
    """
    뉴스 검색 화면을 반환한다.
    """

    return render(
        request,
        "news/news_search.html",
        {},
    )

mysite/templates/base.html
{% load static %}

<!DOCTYPE html>

<html lang="ko" class="h-100">

<head>
    <meta charset="utf-8" />
    <meta name="viewport"
        content="width=device-width, initial-scale=1 minimum-scale=1, maximum-scale=1, user-scalable=no">

    <title>
        {% block title %}Jeby{% endblock title %}
    </title>

    <link rel="shortcut icon" href="{% static 'images/swallow_16px.png' %}" />
    <link rel="icon" sizes="152x152" href="{% static 'images/swallow_152px.png' %}" />

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link
        href="https://fonts.googleapis.com/css2?family=Nanum+Gothic:wght@400;700&family=Noto+Sans+KR:wght@300;400;500&display=swap"
        rel="stylesheet">

    <link rel="stylesheet" href="{% static 'bootstrap/bootstrap-5.0.2/css/bootstrap.min.css' %}" />

    {% block custom_css %}{% endblock custom_css %}
</head>

{% block body %}
{% endblock body %}

{% block script %}
<script src="https://kit.fontawesome.com/**********.js" crossorigin="anonymous"></script>
<script src="{% static 'bootstrap/bootstrap-5.0.2/js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'jquery/jquery-3.6.0/jquery-3.6.0.min.js' %}"></script>
{% endblock script %}

</html>

mysite/templates/base_news.html
{% extends 'base.html' %}

{% load static %}

{% block custom_css %}
<link rel="stylesheet" href="{% static 'news/css/base_news.css' %}" />
{% endblock custom_css %}

{% block body %}

<body class="d-flex flex-column h-100">
    {% include 'include/navbar.html' %}

    <div class="container" id="error_msg">
        <div class="row">
            <div class="col">
                {% include "include/form_errors.html" %}
            </div>
        </div>
    </div>

    <main class="h-100">
        {% block content %}
        {% endblock content %}
    </main>

    {% block footer %}
    {% include 'include/footer.html' %}
    {% endblock footer %}

</body>
{% endblock body %}

{% block script %}
{{ block.super }}

{% endblock script %}

mysite/templates/common/login.html
{% extends 'base.html' %}

{% load static %}

{% block custom_css %}
<link rel="stylesheet" href="{% static 'common/css/login.css' %}" />
{% endblock custom_css %}

{% block body %}

<body class="text-center">
    <div class="container">
        <div class="row">
            <div class="col">
                {% include "include/form_errors.html" %}
            </div>
        </div>
        <div class="row">
            <main class="form-signin">
                <form method="post" action="{% url 'common:login' %}">
                    {% csrf_token %}
                    <img class="mb-2" src="{% static 'images/swallow_152px.png' %}" alt="" width="120" height="120">
                    <div class="form-floating">
                        <input type="text" class="form-control" id="username" placeholder="ID" name="username"
                            value="{{ form.username.value|default_if_none:'' }}">
                        <label for="username">ID</label>
                    </div>
                    <div class="form-floating">
                        <input type="password" class="form-control" id="password" placeholder="Password" name="password"
                            value="{{ form.password.value|default_if_none:'' }}">
                        <label for="password">Password</label>
                    </div>
                    <button class="w-100 btn btn-lg btn-primary" type="submit">Log in</button>
                    <p class="mt-5 mb-3 text-muted"></p>
                </form>
            </main>
        </div>
    </div>
</body>
{% endblock body %}

mysite/templates/include/footer.html
<footer class="footer mt-auto py-2 bg-light border-top border-1">
    <div class="container text-center">
        <span class="text-muted">@ 2021 future talented person</span>
    </div>
</footer>

mysite/templates/include/form_errors.html
{% if form.errors %}
{% for field in form %}
{% for error in field.errors %}
<div class="alert alert-danger" style="padding: 10px 16px">
    <strong>{{ field.label }}</strong>
    {{ error }}
</div>
{% endfor %}
{% endfor %}
{% for error in form.non_field_errors %}
<div class="alert alert-danger" style="padding: 10px 16px">
    <strong>{{ error }}</strong>
</div>
{% endfor %}
{% endif %}

mysite/templates/include/navbar.html
{% load static %}

<nav class="navbar navbar-expand-md navbar-light fixed-top bg-light border-bottom border-1 mb-0">
    <div class="container">
        <a class="navbar-brand" href="{% url 'news:news_search' %}">
            <img src="{% static 'images/swallow_152px.png' %}" alt="" height="31" class="d-inline-block align-text-top">
            <span>Jeby</span>
        </a>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto">
                <li class="nav-item">
                    <a class="nav-link" aria-current="page" href="{% url 'news:news_search' %}">뉴스검색</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" aria-current="page" href="#">키워드관리</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" aria-current="page" href="#">수신자관리</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" aria-current="page" href="#">이메일설정</a>
                </li>
            </ul>
        </div>
        <form class="d-flex">
            {% csrf_token %}
            <button class="navbar-toggler me-2" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarToggleExternalContent" aria-controls="navbarToggleExternalContent"
                aria-expanded="false" aria-label="Toggle navigation" id="toggle-button">
                <span class="navbar-toggler-icon"></span>
            </button>
            {% if user.is_authenticated %}
            <a href="{% url 'common:logout' %}" class="btn btn-outline-secondary nav-button me-2" type="button">
                logout
            </a>
            {% endif %}
        </form>
    </div>
    <div class="collapse navbar-toggler p-0 mt-2 w-100 border-bottom-0" id="navbarToggleExternalContent">
        <div class="py-2 px-3">
            <div class="nav-item-mobile"><a href="{% url 'news:news_search' %}">뉴스검색</a></div>
            <div class="nav-item-mobile"><a href="#">키워드관리</a></div>
            <div class="nav-item-mobile"><a href="#">수신자관리</a></div>
            <div class="nav-item-mobile"><a href="#">이메일설정</a></div>
        </div>
    </div>
</nav>

mysite/templates/news/news_search.html
{% extends 'base_news.html' %}

{% load static %}

{% block custom_css %}
{{ block.super }}
<link rel="stylesheet" href="{% static 'news/css/news_search.css' %}" />
{% endblock custom_css %}

{% block content %}
<div class="container" id="search-box">

</div>


{% endblock content %}

{% block footer %}
{% endblock footer %}

{% block script %}
{{ block.super }}
<script src="{% static 'news/js/news_search.js' %}"></script>
{% endblock script %}